services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mendyfi:local
    volumes:
      - mendyfi-data:/opt/mendyfi
    ports:
      - "3000:3000"
      - "1812:1812/udp"
      - "1813:1813/udp"
    restart: unless-stopped

volumes:
  mendyfi-data: