services:
  app:
    image: alpine:latest
    working_dir: /app
    volumes:
      - ./mendyfi:/app/mendyfi
    ports:
      - "3000:3000"
      - "1812:1812/udp"
      - "1813:1813/udp"
    command: ./mendyfi
    restart: unless-stopped